// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbrHW14G8-vAp2B3W6z7cxEomImFhZIVI',
    appId: '1:713678561456:web:381cf87af8d8c98d411b75',
    messagingSenderId: '713678561456',
    projectId: 'prueba-pr-7674c',
    authDomain: 'prueba-pr-7674c.firebaseapp.com',
    databaseURL: 'https://prueba-pr-7674c-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-pr-7674c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWJ4aH_kbV7EeG0J0n_6qiQHdtI3jam1U',
    appId: '1:713678561456:android:2ffa67801f2bc21f411b75',
    messagingSenderId: '713678561456',
    projectId: 'prueba-pr-7674c',
    databaseURL: 'https://prueba-pr-7674c-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-pr-7674c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI9UUU_gupcJUAK_QKxOZRs3034etG4DY',
    appId: '1:713678561456:ios:cb800f3019be0da3411b75',
    messagingSenderId: '713678561456',
    projectId: 'prueba-pr-7674c',
    databaseURL: 'https://prueba-pr-7674c-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-pr-7674c.appspot.com',
    iosBundleId: 'com.example.prueba2App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI9UUU_gupcJUAK_QKxOZRs3034etG4DY',
    appId: '1:713678561456:ios:cb800f3019be0da3411b75',
    messagingSenderId: '713678561456',
    projectId: 'prueba-pr-7674c',
    databaseURL: 'https://prueba-pr-7674c-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-pr-7674c.appspot.com',
    iosBundleId: 'com.example.prueba2App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbrHW14G8-vAp2B3W6z7cxEomImFhZIVI',
    appId: '1:713678561456:web:5377e0ce76262bf9411b75',
    messagingSenderId: '713678561456',
    projectId: 'prueba-pr-7674c',
    authDomain: 'prueba-pr-7674c.firebaseapp.com',
    databaseURL: 'https://prueba-pr-7674c-default-rtdb.firebaseio.com',
    storageBucket: 'prueba-pr-7674c.appspot.com',
  );
}
